import DS from 'ember-data';

export default DS.Model.extend({
  season: DS.attr('string'), // Determines which season of abinpc this data belongs to
  name: DS.attr('string'),
  accessKey: DS.attr('string'),
  score: DS.attr('number'),
  
  // picks:
  pick1: '--Select Game--',
  pick2: '--Select Game--',
  pick3: '--Select Game--',
  pick4: '--Select Game--',
  pick5: '--Select Game--',
  pick6: '--Select Game--',
  pick7: '--Select Game--',
  pick8: '--Select Game--',
  pick9: '--Select Game--',
  pick10: '--Select Game--',
  pick11: '--Select Game--',
  pick12: '--Select Game--',
  pick13: '--Select Game--',
  pick14: '--Select Game--',
  pick15: '--Select Game--',
  pick16: '--Select Game--',
  pick17: '--Select Game--',
  pick18: '--Select Game--',
  pick19: '--Select Game--',
  pick20: '--Select Game--',
  pick21: '--Select Game--',
  pick22: '--Select Game--',
  pick23: '--Select Game--',
  pick24: '--Select Game--',
  pick25: '--Select Game--',
  pick26: '--Select Game--',
  pick27: '--Select Game--',
  pick28: '--Select Game--',
  pick29: '--Select Game--',
  pick30: '--Select Game--',
  pick31: '--Select Game--',
  pick32: '--Select Game--',
  pick33: '--Select Game--',
  pick34: '--Select Game--',
  pick35: '--Select Game--',
  pick36: '--Select Game--',
  pick37: '--Select Game--',
  pick38: '--Select Game--',
  pick39: '--Select Game--',
  pick40: '--Select Game--',
  pick41: '--Select Game--',
  pick42: '--Select Game--',
  pick43: '--Select Game--',
  pick44: '--Select Game--',
  pick45: '--Select Game--',
  pick46: '--Select Game--',
  pick47: '--Select Game--',
  pick48: '--Select Game--',
  pick49: '--Select Game--',
  pick50: '--Select Game--',
  pick51: '--Select Game--',
  pick52: '--Select Game--',
  pick53: '--Select Game--',
  pick54: '--Select Game--',
  pick55: '--Select Game--',
  pick56: '--Select Game--',
  pick57: '--Select Game--',
  pick58: '--Select Game--',
  pick59: '--Select Game--',
  pick60: '--Select Game--',
  pick61: '--Select Game--',
  pick62: '--Select Game--',
  pick63: '--Select Game--'
});
