import DS from 'ember-data';
/*
Teamset is where the team names will be stored. The letter in each variable refers to the region.
The number refers to the seed. So team B5 is the 5 seed in the second region. Check out
models/regionset to see how the regions are numbered.
*/
export default DS.Model.extend({
  season: DS.attr('string'), // Determines which season of abinpc this data belongs to
  A1: DS.attr('string'),
  A2: DS.attr('string'),
  A3: DS.attr('string'),
  A4: DS.attr('string'),
  A5: DS.attr('string'),
  A6: DS.attr('string'),
  A7: DS.attr('string'),
  A8: DS.attr('string'),
  A9: DS.attr('string'),
  A10: DS.attr('string'),
  A11: DS.attr('string'),
  A12: DS.attr('string'),
  A13: DS.attr('string'),
  A14: DS.attr('string'),
  A15: DS.attr('string'),
  A16: DS.attr('string'),
  B1: DS.attr('string'),
  B2: DS.attr('string'),
  B3: DS.attr('string'),
  B4: DS.attr('string'),
  B5: DS.attr('string'),
  B6: DS.attr('string'),
  B7: DS.attr('string'),
  B8: DS.attr('string'),
  B9: DS.attr('string'),
  B10: DS.attr('string'),
  B11: DS.attr('string'),
  B12: DS.attr('string'),
  B13: DS.attr('string'),
  B14: DS.attr('string'),
  B15: DS.attr('string'),
  B16: DS.attr('string'),
  C1: DS.attr('string'),
  C2: DS.attr('string'),
  C3: DS.attr('string'),
  C4: DS.attr('string'),
  C5: DS.attr('string'),
  C6: DS.attr('string'),
  C7: DS.attr('string'),
  C8: DS.attr('string'),
  C9: DS.attr('string'),
  C10: DS.attr('string'),
  C11: DS.attr('string'),
  C12: DS.attr('string'),
  C13: DS.attr('string'),
  C14: DS.attr('string'),
  C15: DS.attr('string'),
  C16: DS.attr('string'),
  D1: DS.attr('string'),
  D2: DS.attr('string'),
  D3: DS.attr('string'),
  D4: DS.attr('string'),
  D5: DS.attr('string'),
  D6: DS.attr('string'),
  D7: DS.attr('string'),
  D8: DS.attr('string'),
  D9: DS.attr('string'),
  D10: DS.attr('string'),
  D11: DS.attr('string'),
  D12: DS.attr('string'),
  D13: DS.attr('string'),
  D14: DS.attr('string'),
  D15: DS.attr('string'),
  D16: DS.attr('string')
});
